### ISSUE TITLE
After successful payment, the user is redirected to a "localhost" page instead of the intended confirmation or order page. 

### ISSUE THREAD

**Issue by sourabhbhat** [Abdullah-dev0/Effortless-Events#1]
This behavior prevents the user from completing the checkout process.

- Is this an error or should the routes be defined?

**Comment by Abdullah-dev0** [comment]
let me check

**Comment by Abdullah-dev0** [comment]
> This behavior prevents the user from completing the checkout process.
> 
> * Is this an error or should the routes be defined?

the issue is resolved that was not an error i was just testing stripe api  and i forgot to change success url thank you for notifying ! 
You can check now.

**Comment by Abdullah-dev0** [comment]
the issue is resolved that was not an error i was just testing stripe api and i forgot to change success url thank you for notifying !
You can check now.
