### ISSUE TITLE
This is not exactly a issue but it would be cool if you added Update and Delete operations to the personal events created.

### ISSUE THREAD

**Issue by sourabhbhat** [Abdullah-dev0/Effortless-Events#2]
- Now if we create any event we are not able to update or delete it I think, but I think the app would be complete if we added that.
- another cool feature I wanted to add but have a vague idea about implementing is generating a QR code ticket upon successful completion of the order. Like using any npm package that generates a QR code and upon scanning generates a ticket kinda thing would be really cool.

But kudos on completing this !!

**Comment by Abdullah-dev0** [comment]
> * Now if we create any event we are not able to update or delete it I think, but I think the app would be complete if we added that.
> * another cool feature I wanted to add but have a vague idea about implementing is generating a QR code ticket upon successful completion of the order. Like using any npm package that generates a QR code and upon scanning generates a ticket kinda thing would be really cool.
> 
> But kudos on completing this !!

we can delete and update the event see carefully you will see two icons 
![image](https://github.com/Abdullah-dev0/Effortless-Events/assets/116773738/f913f02b-0392-4f2c-9850-0a29aa729912)

**Comment by sourabhbhat** [comment]
Oh yeah.. I hadn't observed that thanks for informing me! what do you think of the QR code feature?

**Comment by Abdullah-dev0** [comment]
> Oh yeah.. I hadn't observed that thanks for informing me! what do you think of the QR code feature?

**Comment by Abdullah-dev0** [comment]
its really cool tbh i will look into it thanks for contributing ❤
