### ISSUE TITLE
Not able to create event

### ISSUE THREAD

**Issue by sourabhbhat** [Abdullah-dev0/Effortless-Events#3]
Even after I cloned the repo and replaced the env file with all the required credentials, I am not able to create an event.It is leading me to the home page itself.I checked the page.tsx file inside the create event folder and I'm guessing it has to do something with authentication? Like it allows a user to create an event only if it can retrieve the userId after successful authentication.But I'm able to sign in easily so that shouldn't be an issue I think.

Can you help me resolve this?

edit 1: I got this in the console of devtools
🔒 Clerk:
The SignUp and SignIn components cannot render when a user is already signed in, unless the application allows multiple sessions. Since a user is signed in and this application only allows a single session, Clerk is redirecting to the Home URL instead.
(This notice only appears in development)

**Comment by Abdullah-dev0** [comment]
> Even after I cloned the repo and replaced the env file with all the required credentials, I am not able to create an event.It is leading me to the home page itself.I checked the page.tsx file inside the create event folder and I'm guessing it has to do something with authentication? Like it allows a user to create an event only if it can retrieve the userId after successful authentication.But I'm able to sign in easily so that shouldn't be an issue I think.
> 
> Can you help me resolve this?
> 
> edit 1: I got this in the console of devtools 🔒 Clerk: The SignUp and SignIn components cannot render when a user is already signed in, unless the application allows multiple sessions. Since a user is signed in and this application only allows a single session, Clerk is redirecting to the Home URL instead. (This notice only appears in development)

so issue is on your side only i guess ?

**Comment by sourabhbhat** [comment]
I don't know..I tried enabling multiple sessions in clerk dashboard even then,no luck.

**Comment by Abdullah-dev0** [comment]
> I don't know..I tried enabling multiple sessions in clerk dashboard even then,no luck.

let me check !

**Comment by sourabhbhat** [comment]
should I share anything?

**Comment by Abdullah-dev0** [comment]
> should I share anything?

working perfectly fine from my side you can i see just created new event

**Comment by sourabhbhat** [comment]
Is it compulsory to create webhook secret for clerk? Because I didn't create one..If yes could you tell me how to create a webhook endpoint?
Even I didn't create one for stripe

**Comment by Abdullah-dev0** [comment]
> Is it compulsory to create webhook secret for clerk? Because I didn't create one..If yes could you tell me how to create a webhook endpoint?

yes your database _id and clerk are working together it is complesary to create one. if you having issue you can watch javascript mastery -> https://www.youtube.com/watch?v=zgGhzuBZOQg

**Comment by sourabhbhat** [comment]
Okay I will.. but how am I able to sign in without providing webhook secret?

**Comment by Abdullah-dev0** [comment]
> Okay I will.. but how am I able to sign in without providing webhook secret?

so basically what i'm doing in this aap we are saving every user in clerk but also in our database and we make relation of our database user and clerk user to make querys.

watch the video . i need to close this issue

**Comment by sourabhbhat** [comment]
Okay

**Comment by Abdullah-dev0** [comment]
> Okay

thanks
